apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx-affinity
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "node-role.kubernetes.io/control-plane"
            operator: Exists          # In, NotIn, Exists, DoesNotExist, Gt and Lt

        # - matchExpressions:
        #   - key: disktype
        #     operator: In          # In, NotIn, Exists, DoesNotExist, Gt and Lt
        #     values:               # In => key=value,    NotIn => key!=value
        #     - ssd                 # Exists => only 
