apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-app-webcolor-podAffinity
spec:
  selector:
    matchLabels:
      app: app-webcolor-podAffinity
  replicas: 3
  template:
    metadata:
      labels:
        app: app-webcolor-podAffinity
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - app-webcolor-podAffinity
            topologyKey: "kubernetes.io/hostname"
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - store
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: app-webcolor
        image: ghcr.io/wiktorvip/app-webcolor
