apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-test-config
  namespace: default
data:
  A_A_SPECIAL_LEVEL: very
  A_A_SPECIAL_TYPE: charm
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-cm-test
spec:
  containers:
    - name: test-container
      image: busybox
      command: [ "/bin/sh", "-c", "env" ]
      envFrom:
      - configMapRef:
          name: cm-test-config
  restartPolicy: Never
