apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-test-config-mount
  namespace: default
data:
  var1: AAA
  var2: BBB
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-cm-test-mount
spec:
  volumes:
  - name: cm-volume
    configMap:
      name: cm-test-config-mount
  containers:
    - name: test-container
      image: busybox
      command:
        - sh
        - -c
        - echo Hello Kubernetes! && sleep 3600
      volumeMounts:
      - name: cm-volume
        readOnly: true
        mountPath: "/etc/cm-volume"

# kubectl exec pod-cm-test-mount -- printenv | grep var
# kubectl exec pod-cm-test-mount -- cat /etc/cm-volume/var1
# kubectl exec pod-cm-test-mount -- cat /etc/cm-volume/var2
