apiVersion: v1
kind: ConfigMap
metadata:
  name: app-webcolor-cm
data:
  APP_COLOR: blue
  APP_MODE: prod
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: app-webcolor-cm-envf
  name: app-webcolor-cm-envf
spec:
  containers:
  - name: app-webcolor
    image: ghcr.io/wiktorvip/app-webcolor
    ports:
    - containerPort: 9000
    envFrom:
    - configMapRef:
        name: app-webcolor-cm
---
apiVersion: v1
kind: Service
metadata:
  name: svc-app-webcolor-cm
spec:
  selector:
    app: app-webcolor-cm-envf
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30081
