apiVersion: v1
kind: Pod
metadata:
  name: pod-envar-demo
  labels:
    purpose: demonstrate-envars
spec:
  containers:
  - name: envar-demo-container
    image: gcr.io/google-samples/node-hello:1.0
    env:
    - name: DEMO_1
      value: "Hello from the environment DEMO_1"
    - name: DEMO_2
      value: "Hello from the environment DEMO_2"


# kubectl exec pod-envar-demo -- printenv
