apiVersion: v1
kind: Pod
metadata:
  labels:
    app: app-webcolor-env
  name: app-webcolor-env
spec:
  containers:
  - name: app-webcolor
    image: ghcr.io/wiktorvip/app-webcolor
    ports:
     - containerPort: 9000
    env:
     - name: APP_COLOR
       value: "red"
---
apiVersion: v1
kind: Service
metadata:
  name: np-svc-app-webcolor-env
spec:
  selector:
    app: app-webcolor-env
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30080

