apiVersion: batch/v1
kind: Job
metadata:
  name: job-math-add
spec:
  completions: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: math-add
          image: ubuntu
          command: ['expr', '3', '+', '2']
