apiVersion: v1
kind: Secret
metadata:
    name: app-mysql-secret
data:
    DB_Host: c3ZjLW15c3FsLXNlcnZlcgo=
    DB_Password: cGFzc3dvcmQK
    DB_User: cm9vdA==

# echo 'svc-mysql-server' | base64
# echo 'c3ZjLW15c3FsCg==' | base64 --decode

---
apiVersion: v1
kind: Pod
metadata:
  name: app-web-mysql
  labels:
    app: app-web-mysql
spec:
  containers:
  - name: app-web-mysql
    image: ghcr.io/wiktorvip/app-web-mysql:v1
    ports:
    - containerPort: 9070
    envFrom:
      - secretRef:
          name: app-mysql-secret
---
kind: Service
apiVersion: v1
metadata:
  name: svc-app-web-mysql
spec:
  selector:
    app: app-web-mysql
  type: NodePort
  ports:
  - port: 9070
    targetPort: 9070
    nodePort: 30070
