apiVersion: v1
kind: Pod
metadata:
  name: pod-envfrom-secret
spec:
  volumes:
  - name: secret-volume
    secret:
      secretName: prod-db-secret
  containers:
  - name: envars-test-container
    image: nginx
    volumeMounts:
    - name: secret-volume
      readOnly: true
      mountPath: "/etc/secret-volume"

# kubectl create secret generic prod-db-secret --from-literal=username=produser --from-literal=password=Y4nys7f11

#Container will have the following files present on their filesystems with the values for each container's environment:
#/etc/secret-volume/username
#/etc/secret-volume/password

# kubectl exec pod-envfrom-secret -- cat /etc/secret-volume/password
# kubectl exec pod-envfrom-secret -- cat /etc/secret-volume/username