apiVersion: v1
kind: Pod
metadata:
  labels:
    app: busybox
    env: test
  name: pod-liveness-exec
spec:
  containers:
  - name: liveness
    image: busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5  # field tells the kubelet that it should wait 5 seconds before performing the first probe
      periodSeconds: 5        #  field specifies that the kubelet should perform a liveness probe every 5 seconds.
