apiVersion: v1
kind: Pod
metadata:
  name: pod-cpu-demo
  labels:
    app: stress
    env: test
spec:
  containers:
  - name: cpu-demo-ctr
    image: vish/stress
    resources:
      limits:
        cpu: "1"
      requests:
        cpu: "0.5"
    args:
    - -cpus
    - "2"