apiVersion: v1
kind: Pod
metadata:
  name: pod-log
  labels:
    app: event-simulator
    env: prod
spec:
  containers:
  - name: app-event-simulator
    image: ghcr.io/wiktorvip/app-event-simulator:1.0
