apiVersion: v1
kind: Pod
metadata:
  name: pod-command
  labels:
    app: busybox
    env: dev
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - sh
      - -c
      - echo Hello Kubernetes! && sleep 3600
