apiVersion: v1
kind: Pod
metadata:
  name: pod-port
  labels:
    app: app-webcolor-port
    env: test
spec:
  containers:
  - image: ghcr.io/wiktorvip/app-webcolor
    name: app-webcolor
    ports:
    - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: np-svc-app-webcolor-port
spec:
  selector:
    app: app-webcolor-port
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30010
