apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deployment-app-webcolor-tt
  name: deployment-app-webcolor-tt
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-webcolor-tt
  template:
    metadata:
      labels:
        app: app-webcolor-tt
    spec:
      containers:
      - image: ghcr.io/wiktorvip/app-webcolor:v4
        name: app-webcolor
        ports:
          - containerPort: 9000
