apiVersion: v1
kind: Namespace
metadata:
  labels:
    ns: app
  name: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-webcolor-darkblue
  name: app-webcolor-darkblue
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-webcolor-darkblue
  template:
    metadata:
      labels:
        app: app-webcolor-darkblue
    spec:
      containers:
      - image: ghcr.io/wiktorvip/app-webcolor:darkblue
        name: app-webcolor
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: svc-app-webcolor-darkblue
  namespace: app
spec:
  selector:
    app: app-webcolor-darkblue
  type: ClusterIP
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
