apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: quota
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-test
  namespace: quota
spec:
  hard:
    cpu: "1000"
    memory: 5Gi
    pods: "10"
    configmaps: "10" 
    persistentvolumeclaims: "4" 
    secrets: "10" 
    services: "10"

