apiVersion: v1
kind: Pod
metadata:
  name: example-conflict-with-limitrange-cpu
  namespace: limit
spec:
  containers:
  - name: demo
    image: registry.k8s.io/pause:2.0
    resources:
      requests:
        cpu: 700m