apiVersion: v1
kind: Pod
metadata:
  name: pod-busybox
  labels:
    app: pod-busybox
    role: busybox
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh','-c', "sleep 1800m"]
    imagePullPolicy: IfNotPresent
