apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc-app-webcolor
  labels:
    app: nodeport-svc-app-webcolor
spec:
  selector:
    app: app-webcolor-svc   # Pod with that label needs exist
  type: NodePort
  ports:
  - port: 9000
    # By default and for convenience, the `targetPort` is set to
    # the same value as the `port` field.
    targetPort: 9000
    protocol: TCP
    # Optional field
    # By default and for convenience, the Kubernetes control plane
    # will allocate a port from a range (default: 30000-32767)
    nodePort: 30099
