apiVersion: v1
kind: Pod
metadata:
  name: pod-mysql-server
  labels:
    app: mysql
    role: db
spec:
  containers:
  - name: mysql
    image: mysql
    ports:
    - containerPort: 3306
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: password
#     - name: MYSQL_ALLOW_EMPTY_PASSWORD
#       value: "1"
---
kind: Service
apiVersion: v1
metadata:
  name: svc-mysql-server
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
