apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx
  labels:
    app: deployment-nginx
spec:
  replicas: 3                   # specifies how many pods to run
  selector:
    matchLabels:
      app: deployment-nginx     # has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: deployment-nginx   # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: nginx
        image: nginx:1.24
        ports:
        - containerPort: 80
