apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx-affinity
  labels:
    app: nginx-affinity
spec:
  selector:
    matchLabels:
      app: nginx-affinity
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx-affinity
    spec:
      affinity:
        nodeAffinity:         # specifies desired criteria of a node which will cause the pod to be scheduled on it
          requiredDuringSchedulingIgnoredDuringExecution:   # specifies that affinity is relevant when scheduling a new pod, but is ignored when the pod is already running.
            nodeSelectorTerms:  # specifies, in this case, that the node needs to have a disk of type SSD for the pod to be scheduled
            - matchExpressions:
              - key: color
                operator: In
                values:
                - blue  
      containers:
       - name: nginx
         image: nginx:1.24
         ports:
          - containerPort: 80

# kubectl label node k8s-w1 color=blue
