apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx-pv
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: nginx-pv
  replicas: 5
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx-pv
    spec:
      volumes:                        # defines a name for the volume, which is referenced below in containers.volumeMounts 
       - name: nginx-storage
         persistentVolumeClaim:       # references a PVC. For this to work, you must have some PVs in your cluster and create a PVC object that matches those PVs.
           claimName: nginx-pvc
      containers:
       - name: nginx
         image: nginx:1.24
         ports:
         - containerPort: 80
         volumeMounts:
         - mountPath: "/usr/share/nginx/html"
           name: nginx-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
  #storageClassName: ""   # When a PVC does not specify a storageClassName, the default StorageClass is used.
---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pv0003
# spec:
#   capacity:
#     storage: 1Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Recycle
#   storageClassName: "nfs-client"
