apiVersion: v1
kind: Pod
metadata:
  name: pod-curl
  namespace: default
spec:
  containers:
  - command:
    - sleep
    - "5000"
    image: byrnedo/alpine-curl:latest
    imagePullPolicy: Always
    name: alpine-curl
