apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-webcolor-rolling
  name: app-webcolor-rolling
spec:
  replicas: 5
  selector:
    matchLabels:
      app: app-webcolor-rolling
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # The default value is 25%.
      # The maximum number of pods that can be unavailable during the rolling deployment. This can be either a percentage (10%) or a whole number (1).
      maxUnavailable: 20% # The value can be an absolute number (for example, 5) or a percentage of desired Pods (for example, 10%). 
      # The maximum number of pods that can be scheduled above the original number of pods while the rolling deployment is in progress. This can be either a percentage (10%) or a whole number (1).
      maxSurge: 20% # The value can be an absolute number (for example, 5) or a percentage
  template:
    metadata:
      labels:
        app: app-webcolor-rolling
        code: webcolor
    spec:
      containers:
      - image: ghcr.io/wiktorvip/app-webcolor:v1
        name: app-webcolor
        ports:
          - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: svc-app-webcolor-rolling
  namespace: default
spec:
  ports:
  - nodePort: 30050
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: app-webcolor-rolling
  type: NodePort
