apiVersion: v1
kind: Service
metadata:
  name: svc-app-webcolor-blue-green
  namespace: default
spec:
  ports:
  - nodePort: 30020
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    version: v1
  type: NodePort
