apiVersion: v1
kind: Service
metadata:
  name: svc-app-webcolor-canary
  namespace: default
spec:
  ports:
  - nodePort: 30030
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    code: app-webcolor
  type: NodePort
