apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-webcolor-dark
  name: app-webcolor-dark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-webcolor-dark
  template:
    metadata:
      labels:
        app: app-webcolor-dark
        version: v2
        code: app-webcolor
    spec:
      containers:
      - image: ghcr.io/wiktorvip/app-webcolor:dark
        name: app-webcolor
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
