apiVersion: v1
kind: Pod
metadata:
  name: black
spec:
  containers:
  - args:
    - --vm
    - "1"
    - --vm-bytes
    - 30M
    - --vm-hang
    - "1"
    command:
    - stress
    image: polinux/stress
    imagePullPolicy: Always
    name: mem-stress
    resources:
      limits:
        memory: 40Mi
      requests:
        memory: 40Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: blue
spec:
  containers:
  - args:
    - --vm
    - "1"
    - --vm-bytes
    - 30M
    - --vm-hang
    - "1"
    command:
    - stress
    image: polinux/stress
    imagePullPolicy: Always
    name: mem-stress
    resources:
      limits:
        memory: 40Mi
      requests:
        memory: 40Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: white
spec:
  containers:
  - args:
    - --vm
    - "1"
    - --vm-bytes
    - 250M
    - --vm-hang
    - "1"
    command:
    - stress
    image: polinux/stress
    imagePullPolicy: Always
    name: mem-stress
    resources:
      limits:
        memory: 300Mi
      requests:
        memory: 300Mi
