apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cl-role-developer-access
rules:
- apiGroups:
  - "apps"              # A list of API groups to which the resources belong. The " " refers to the core API group, which contains resources such as pods, services, nodes, etc.
  resources:
  - services        # A list of resources to which the rule applies, such as pods, services, and secrets.
  verbs:            # A list of verbs that the rule allows, such as list, get, watch, create, update, and delete.
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update

# kubectl create clusterrole cl-role-developer-access --resource=services,deployments --verb=create,delete,deletecollection,get,list,patch,update
