apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb-cl-role-developer-access-to-john
subjects:
- kind: User
  name: john
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cl-role-developer-access
  apiGroup: rbac.authorization.k8s.io

# kubectl create clusterrolebinding crb-cl-role-developer-access-to-john --user=john --clusterrole=cl-role-developer-access