apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb-cl-role-stor-admin-access-to-deepak
subjects:
- kind: User
  name: Deepak
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cl-role-storage-admin
  apiGroup: rbac.authorization.k8s.io

# kubectl create clusterrolebinding crb-cl-role-stor-admin-access-to-deepak --user=Deepak --clusterrole=cl-role-storage-admin