apiVersion: apps/v1
kind: Deployment
metadata:
  name: emptydir-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: emptydir-test
  template:
    metadata:
      labels:
        app: emptydir-test
    spec:
      containers:
      - name: nginx
        image: nginx:1.24
        volumeMounts:
        - mountPath: /cache
          name: cache-volume
      volumes:
       - name: cache-volume
         emptyDir:
          sizeLimit: 50Mi

# The location should of emptyDir should be in 
# /var/lib/kubelet/pods/{podid}/volumes/kubernetes.io~empty-dir/ 
# on the given node where your pod is running.
