apiVersion: v1
kind: Pod
metadata:
  name: pod-data-volume
spec:
  containers:
  - name: busybox
    image: busybox
    args:
    - sleep
    - "1000"
    volumeMounts:
    - mountPath: /opt
      name: data-volume
  volumes:
  - name: data-volume
    hostPath:
      path: /data         # directory location on host
      type: Directory     # this field is optional
