apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostpath-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hostpath-test
  template:
    metadata:
      labels:
        app: hostpath-test
    spec:
      containers:
      - name: nginx
        image: nginx:1.24
        volumeMounts:
        - mountPath: "/opt/test"
          name: index-volume
      volumes:
       - name: index-volume
         hostPath:
          path: /srv # directory location on host
          type: Directory # this field is optional
