apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
  #storageClassName: "nfs-client"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx-pv
  labels:
    app: deployment-nginx-pv
spec:
  selector:
    matchLabels:
      app: nginx-pv
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx-pv
    spec:
      volumes:                        # defines a name for the volume, which is referenced below in containers.volumeMounts 
       - name: nginx-storage
         persistentVolumeClaim:       # references a PVC. For this to work, you must have some PVs in your cluster and create a PVC object that matches those PVs.
           claimName: nginx-pvc
      containers:
       - name: nginx
         image: nginx:1.24
         ports:
         - containerPort: 80
         volumeMounts:
         - mountPath: "/usr/share/nginx/html"
           name: nginx-storage
---
apiVersion: v1
kind: Service
metadata:
  name: svc-anginx-pv
  namespace: default
spec:
  ports:
  - nodePort: 30055
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: deployment-nginx-pv
  type: NodePort


